### ISSUE TITLE
Math module implementation

### ISSUE THREAD

**Issue by Trixt0r** [czyzby/ktx#29]
Hi guys,

I am a little bit confused about the implementation of the math module.
Applying operators on vectors/matrices does not behave as expected since the result which gets returned is the left handed variable instead of a new vector/matrix.
For example:
```
val x = Vector2(1f, 1f)
val y = x * 2f
```
will get `y` the correct result and `x` won't be `Vector2(1f, 1f)` anymore but `Vector2(2f, 2f)`, i.e. `x == y` is `true`.

To bypass that problem you would do something like this: `val y = Vector2(x) * 2f` so `x` keeps it's original values.

I understand that the operators are simple aliases for the Vector/Matrix methods and the gdx implementation does not return new instances for obvious performance reasons.

So do you think this problem could be solved with some kind of pooling to prevent performance issues?
I would appreciate at least some kind of flag, which can be set for the math module so new instances get returned by default.

-Trixt0r

**Comment by czyzby** [comment]
I think `Vector2` is mutable _precisely_ because of the immutable values overhead, especially on mobile platforms. As you noticed, KTX math module provides only syntax sugar for LibGDX API, so we're not going to introduce changes like that. Most LibGDX users should already be used to mutable vectors.

Enforcing `Vector2` instances pooling would be pretty annoying and could lead to multiple bugs that could be pretty hard to track - creating a lot of unnecessary objects in long equations (due to no instances freeing), using objects that were accidentally freed and getting random values, and so on. Pooling is definitely on the "don't, unless you really have to" list of JVM practices. Even if we ditched the pooling, returning new instances after each operation could make GC crazy on mobiles. I'm open to suggestions, though, so if you have some code snippets that could solve the issue, I could take a look.

**Comment by czyzby** [comment]
Heh, I've just got a dumb idea to abuse Kotlin DSL capabilities and avoid the new object syntax:

```Kotlin
operator inline fun Vector2.invoke() = Vector2(this)
```

Your example could be rewritten as:

```Kotlin
val x = vec2(x = 1f, y = 1f)
val y = x() * 2f
```

This would give you the control over when `Vector2` instances are created and could be used to create chains of operations that produce exactly one new `Vector2` instance.

Use at your own risk, though.

**Comment by czyzby** [comment]
Assignment operators (`+=`, `-=`, `*=`, `/=`) now mutate vector/matrix instances, while regular binary operators (`+`, `-`, `*`, `/`) create new instances for the result. See #130.
